### ISSUE TITLE
"succ if" doesn't evaluate

### ISSUE THREAD

**Issue by nponeccop** [sirikid/arith#1]
```hs
 >> succ if is_zero zero then zero else zero;
Unevaluable term: TmSucc (TmIf (TmIsZero TmZero) TmZero TmZero)
```

**Comment by sirikid** [comment]
Cause: https://github.com/sirikid/arith/blob/master/src/Arith/Interpreter.hs#L39-L40

**Comment by nponeccop** [comment]
The right solution is to check the dynamic type after reduction of the subterm and not before. Something like `go t >>= validateAndFlattenNumber` instead of guards
